base:
  random_state: 42

data:
  # loading data
  dataset_csv: 'data/raw/iris.csv'
  features_path: 'data/processed/featured_iris.csv'

train:
  # training hyperparmaters
  trainset_path: 'data/processed/train_iris.csv'

test:
  test_size: 0.2
  testset_path: 'data/processed/test_iris.csv'

model:
  clf_params:
    'C': 0.01
    'solver': 'lbfgs'
    'multi_class': 'multinomial'
    'max_iter': 10
  model_path: 'models/model.joblib'

reports:
  # metrics, images, etc
  metrics_file: 'reports/metrics.json'
  confusion_matrix_image: 'reports/confusion_matrix.png'

