base:
  random_state: 42

data:
  # loading data
  dataset_csv: 'data/raw/iris.csv'
  features_path: 'data/processed/featured_iris.csv'

train:
  # training hyperparmaters
  trainset_path: 'data/processed/train_iris.csv'

test:
  test_size: 0.2
  testset_path: 'data/processed/test_iris.csv'

features:
  target_column: target

model:
  cv: 3
  estimator_name: logreg
  estimators:
    logreg:
      param_grid:
         C: [0.001]
         solver: ['lbfgs']
         multi_class: ['multinomial']
         max_iter: [100]
    svm:
      param_grid:
        C: [0.1, 1.0]
        kernel: ['rbf', 'linear']
        gamma: ['scale']
        degree: [3, 5]
  model_path: 'models/model.joblib'

evaluate:
  # metrics, images, etc
  metrics_file: 'metrics.json'
  reports_dir: 'reports'
  confusion_matrix_image: 'confusion_matrix.png'


